package com.example.nerdherd.ObjectManager;

public interface DatabaseListener {
    int DB_EVENT_UPDATE_EXPERIMENT_SUCCESS = 0;
    int DB_EVENT_UPDATE_EXPERIMENT_FAILURE = 1;
    int DB_EVENT_UPDATE_PROFILE_SUCCESS = 2;
    int DB_EVENT_UPDATE_PROFILE_FAILURE = 3;
    int DB_EVENT_EXPERIMENT_CHECK_DATA_CHANGED = 4;
    int DB_EVENT_PROFILE_CHECK_DATA_CHANGED = 5;
    int DB_EVENT_EXPERIMENT_SAVE_SUCCESS = 6;
    int DB_EVENT_EXPERIMENT_SAVE_FAILURE = 7;
    int DB_EVENT_PROFILE_SAVE_NEW_SUCCESS = 8;
    int DB_EVENT_PROFILE_SAVE_NEW_FAILURE = 9;
    int DB_EVENT_EXPERIMENT_LOADED_ON_START = 10;
    int DB_EVENT_PROFILE_LOADED_ON_START = 11;
    int DB_EVENT_EXPERIMENT_ON_START_LOAD_FAILURE = 12;
    int DB_EVENT_PROFILE_ON_START_LOAD_FAILURE = 13;

    void onDatabaseEvent(int eventCode, Object data);
}
